sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test --haddock --no-haddock-deps
